### ISSUE TITLE
directories dependency does not work on Windows

### ISSUE THREAD

**Issue by jonahbeckford** [sanette/bogue#27]
The last version of bogue pulled in the `directories` package. The problem is that package does not work on Windows: https://github.com/OCamlPro/directories/issues/14

That's stuck because `xdg` has become the standard (its logic has made its way into the ocaml compiler for profile calculation). And the authors don't have access to a Windows machine.

Thoughts?

**Comment by sanette** [comment]
Well, that's too bad because I remember we switched to `directories` precisely because we thought it would handle better cross-platform config dirs...
I guess we could switch back to the old scheme

**Comment by jonahbeckford** [comment]
https://v3.ocaml.org/p/xdg/latest/doc/index.html works in both Windows and Unix.

**Comment by sanette** [comment]
wouldn't `xdg` pull in the whole `dune` as a runtime dependency?
(this is a naive question; I don't know what binaries really include)
(for the moment, dune is used only for building)

**Comment by jonahbeckford** [comment]
No, it has no runtime dependencies ... just like `directories`. https://github.com/ocaml/dune/blob/main/xdg.opam

I will send you a PR.
