### ISSUE TITLE
tsdl is pinned to versions that don't work on Windows

### ISSUE THREAD

**Issue by jonahbeckford** [sanette/bogue#28]
https://github.com/sanette/bogue/blob/5c2e8dbee93ec13ffacf1bd55aaabe407cb17dc5/dune-project#L36

I have a couple PRs I made to `tsdl` to get it working on Windows. Those PRs are in `tsdl.1.0.0`.

https://erratique.ch/repos/tsdl/commit/?id=9a5f889025305b7b028e72a7467adda162cf0d88
https://erratique.ch/repos/tsdl/commit/?id=276d473e8443b03b157db8b4cf7c7051d981e57e

**Comment by sanette** [comment]
yes I remember this problem. My idea was that it's probably ok now to force users to have a newer version of SDL, and hence to switch bogue to tsdl.1.0.0

**Comment by sanette** [comment]
bogue is now using tsdl >= 1.0.0, so I'm closing this; feel free to reopen would a problem remain
