### ISSUE TITLE
Unable to style text-input field

### ISSUE THREAD

**Issue by IdaraNabuk** [sanette/bogue#33]
I have been trying to embed a text input field in a box or create a border around the text input field but it seems impossible. Is there a way to do this?

Here's one of the ways I tried achieving it in this [temperature converter PR](https://github.com/IdaraNabuk/Bogue-examples/pull/10)

**Comment by sanette** [comment]
yes, widgets are always put in layouts, and you may style the layout, using the `~background` option of functions like `Layout.resident`, `Layout.flat_of_w` etc.

**Comment by sanette** [comment]
For instance:
```ocaml
open Bogue;;
let t = Widget.text_input () in
let style = Style.(of_bg (color_bg Draw.(opaque (find_color "beige")))
                   |> with_border
                     (mk_border ~radius:12
                        (mk_line ~width:3 ~color:Draw.(opaque blue) ()))) in
let l = Layout.resident ~w:200 ~background:(Layout.style_bg style) t in
let house = Layout.flat ~margins:50 [l] in
Bogue.(run (of_layout house));; 
```
![text_input1](https://github.com/sanette/bogue/assets/7536536/2e79a0c7-1478-4c3a-9f74-66ea3352416c)

and if you want more space around the text_input, you may use the `sep` parameter of `flat_of_w`:

```ocaml
let t = Widget.text_input () in
let style = Style.(of_bg (color_bg Draw.(opaque (find_color "beige")))
                   |> with_border
                     (mk_border ~radius:12
                        (mk_line ~width:3 ~color:Draw.(opaque blue) ()))) in
let l = Layout.flat_of_w ~sep:20 ~background:(Layout.style_bg style) [t] in
let house = Layout.flat ~margins:50 [l] in
Bogue.(run (of_layout house));;
```
![text_input2](https://github.com/sanette/bogue/assets/7536536/15ca3d89-b4a2-46a7-a33e-bd6f03afda28)

**Comment by IdaraNabuk** [comment]
Thank you. This could be added to the example repo. It will be a lot helpful.

**Comment by sanette** [comment]
good idea, I'll try to do this
