### ISSUE TITLE
Can't both underline and color a label or text display widget

### ISSUE THREAD

**Issue by msub2** [sanette/bogue#39]
I apologize if this is just my newness to OCaml, but I can't seem to find a way to accomplish both these stylings at once. I can see in the library that the label style is just an alias for Ttf.Style.t, but when I'm consuming the library and trying to set a style it's asking for a Bogue.Label.style which I can't seem to satisfy. I would try to use a Text_display, but that has the opposite problem of being able to underline it but not color the text!

**Comment by sanette** [comment]
this was a bug (or typo!) thanks, the `style` parameter was forgotten in the signature of `Widget.label`. I've corrected this

**Comment by sanette** [comment]
if you try the latest version, for instance with 
```
opam pin add https://github.com/sanette/bogue.git
```
it should work:
```boguex 6```

![Copie d'écran_20241019_093731](https://github.com/user-attachments/assets/eee11c18-c197-4372-9ada-80a8baf7c5d4)

the code is here:
```ocaml
let example6 () =
  let b = W.check_box () in
  let l = W.label ~fg:(Draw.(opaque (find_color "firebrick")))
      ~style:Tsdl_ttf.Ttf.Style.underline
      "Merry Christmas !" in
  let layout = L.flat_of_w ~align:Draw.Center [b;l] in
  let shortcuts = shortcuts_of_list [exit_on_escape] in
  let board = of_layout ~shortcuts layout in
  run board
```

**Comment by sanette** [comment]
for `Text_display` it's a bit more complicated, we need to implement the `color` tag. I put this on my TODO list ;)

**Comment by msub2** [comment]
Thanks, with a label it's working now!
![image](https://github.com/user-attachments/assets/94420942-ee62-4a88-a4a7-7634a5690f46)

**Comment by sanette** [comment]
> for `Text_display` it's a bit more complicated, we need to implement the `color` tag. I put this on my TODO list ;)

DONE!

see `boguex 47`
![Copie d'écran_20241019_182630](https://github.com/user-attachments/assets/46a193f8-d398-4eea-9b93-bc3926ae3500)
