### ISSUE TITLE
Large sized fonts seem to be taking up more vertical space than expected

### ISSUE THREAD

**Issue by msub2** [sanette/bogue#40]
I'm working on parsing Gemtext headings right now and am trying to figure out how to best display them without having too much empty space between elements. So far I've been using a helper function that tries to approximate how many lines the text will take up and calculating a height based off of that, but results for that are somewhat mixed, and if a header goes onto a second line it tends to just get cut off instead. Is there any way I can have something like an "auto" height calculation here?
![image](https://github.com/user-attachments/assets/4e88c385-4594-4cf6-92f8-5a4940b25546)

**Comment by msub2** [comment]
I tried using `Layout.fit_content` as well but that didn't seem to have any noticeable change

**Comment by sanette** [comment]
For single line text it's better to use a Label. There is no auto size for Text display

**Comment by msub2** [comment]
Ahhh, thank you! I also realized that part of my padding issues appear to be coming from empty lines in the source doc, which I've managed to handle. Will go ahead and close this now
