### ISSUE TITLE
default theme pngs not found

### ISSUE THREAD

**Issue by nilsbecker** [sanette/bogue#5]
when i try to run the minimal hello world, and also boguex 0, it get "SDL ERROR: Couldn't open /Users/nbecker/.opam/413/lib/bogue/../../share/bogue/themes/default/check_on.png". indeed that directory contains only 

background.png bogue-icon.png bogue.conf     images/

**Comment by nilsbecker** [comment]
this is on macos after installing bogue from opam

**Comment by sanette** [comment]
thanks for reporting! indeed these files have been moved and I forgot to update the install script.
I've pushed them to github. Could you try copying them manually?
https://github.com/sanette/bogue/tree/master/share/themes/default
(or re-install from the github version)

**Comment by sanette** [comment]
on the other hand something is wrong, since in principle these files are not needed in the default theme... I'll look into this

**Comment by nilsbecker** [comment]
![image](https://user-images.githubusercontent.com/177614/148054715-b87e153f-763b-476f-908e-8557f6d385a0.png)

the examples load with the github version. this is example 1h. the checkbox looks a little unusual, is this the correct one?

**Comment by sanette** [comment]
indeed this checkbox should not be used in the default style. It should use a font char instead. And also I can see that there is a scaling issue :(

**Comment by sanette** [comment]
The scaling issue seems to be the same as https://github.com/sanette/bogue/issues/6

**Comment by sanette** [comment]
> the checkbox looks a little unusual, is this the correct one?

this should be fixed in the new github version
https://github.com/sanette/bogue/commit/79aececa5478375a997ca4a2567a46a7bc7b47d2
