### ISSUE TITLE
boguex fails to find SVG file

### ISSUE THREAD

**Issue by ColMcp** [sanette/bogue#9]
```
% boguex 38                                                                             [master ✱]
Loading Bogue 20220115 with config dir /Users/colin/.opam/default/share/bogue/themes/default
2022-01-16 12:21:58.754 boguex[41400:5536644] INFO: Using SDL 2.0.20
38 = load SVG at different sizes
Fatal error: exception Failure("SDL ERROR: Couldn't open /Users/colin/.opam/default/share/bogue/themes/default/images/koala.svg")
```
The file does exist at `/Users/colin/.opam/default/share/bogue/assets/images/koala.svg`

**Comment by sanette** [comment]
thanks for the report.
Indeed, I moved these files but forgot to update the examples. In the file `examples/example.ml`
the string `"images/koala.svg"` should be replaced by `"%assets/images/koala.svg"`

**Comment by sanette** [comment]
This is now corrected in the github version, if you want to try.

**Comment by ColMcp** [comment]
Thanks for the quick reply. I can confirm that `boguex 38` works OK from a local clone of your GitHub repository.
